// Code generated by "stringer -output message_gen.go -type=Kind"; DO NOT EDIT.

package admin

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindClientNew-1]
	_ = x[KindGatewayNew-2]
	_ = x[KindForwardNew-3]
	_ = x[KindClientRoute-4]
	_ = x[KindProxyAddForward-5]
	_ = x[KindForwardStop-6]
}

const _Kind_name = "KindClientNewKindGatewayNewKindForwardNewKindClientRouteKindProxyAddForwardKindForwardStop"

var _Kind_index = [...]uint8{0, 13, 27, 41, 56, 75, 90}

func (i Kind) String() string {
	i -= 1
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
