// Code generated by "stringer -output bvvd_gen.go -type=Kind"; DO NOT EDIT.

package bvvd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Data-1]
	_ = x[PingGateway-2]
	_ = x[PingForward-3]
	_ = x[PingServer-4]
	_ = x[PackLossGatewayUplink-5]
	_ = x[PackLossGatewayDownlink-6]
	_ = x[PackLossClientUplink-7]
	_ = x[_kind_end-8]
}

const _Kind_name = "DataPingGatewayPingForwardPingServerPackLossGatewayUplinkPackLossGatewayDownlinkPackLossClientUplink_kind_end"

var _Kind_index = [...]uint8{0, 4, 15, 26, 36, 57, 80, 100, 109}

func (i Kind) String() string {
	i -= 1
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
