// Code generated by "stringer -output location_gen.go -type=Location"; DO NOT EDIT.

package bvvd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Moscow-1]
	_ = x[Frankfurt-2]
	_ = x[Tokyo-3]
	_ = x[NewYork-4]
	_ = x[LosAngeles-5]
	_ = x[_end-6]
}

const _Location_name = "MoscowFrankfurtTokyoNewYorkLosAngeles_end"

var _Location_index = [...]uint8{0, 6, 15, 20, 27, 37, 41}

func (i Location) String() string {
	i -= 1
	if i >= Location(len(_Location_index)-1) {
		return "Location(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Location_name[_Location_index[i]:_Location_index[i+1]]
}
