// Code generated by "stringer -output proto_gen.go -type=Kind"; DO NOT EDIT.

package proto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[_kind_start-1]
	_ = x[Data-2]
	_ = x[PingProxyer-3]
	_ = x[PingForward-4]
	_ = x[PackLossClientUplink-5]
	_ = x[PackLossProxyerUplink-6]
	_ = x[PackLossProxyerDownlink-7]
	_ = x[_kind_end-8]
}

const _Kind_name = "_kind_startDataPingProxyerPingForwardPackLossClientUplinkPackLossProxyerUplinkPackLossProxyerDownlink_kind_end"

var _Kind_index = [...]uint8{0, 11, 15, 26, 37, 57, 78, 101, 110}

func (i Kind) String() string {
	i -= 1
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
